# Generated by Django 4.2.1 on 2023-06-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_activity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='file_url',
            field=models.CharField(default='esagagaeg', max_length=300),
            preserve_default=False,
        ),
    ]
