# Generated by Django 4.2.1 on 2023-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_activity_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.CharField(default='2021-03-12', max_length=50),
            preserve_default=False,
        ),
    ]
