# Generated by Django 4.2.1 on 2023-06-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
    ]
